projectfolder = '~/Data/SimpleTest/';
params = struct(...
    'A', {{ 1, 2, 3}},...
    'B', {{ 1, 2, 3}},...
    'C', {{ 1, 2, 3}}...
    );

Explorer = ParameterExplorer('SimpleTest',params,...
    'projectfolder',projectfolder);
Explorer.run();